### PR TITLE
Implement chassis router

### LINKED ISSUE #43: Route Chassis request depending on OneView resource

### PR DESCRIPTION
**Pull request by danielreed**
Closes #43

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/51)

### CODE REVIEW

**Comment by ffdarkpenguin** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-:-KtwOsqx-9fZ42volKu4:bnfp4nl)*

**Comment by ffdarkpenguin** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by llvieira** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by llvieira** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-:-KtwQYpwwI5A93hjIe01:bnfp4nl)*

**Comment by ricardoas** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 48 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-KtwWgO_XNAAflor0MSa:-KtwWgO_XNAAflor0MSb:b2pm3ot) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L48)):*
> ```Python
> 
>         index_obj = ov_client.index_resources.get_all(filter='uuid=' + uuid)
>         category = index_obj[0]["category"]
> ```

should we avoid the case of searching for an UUID with no correspondence to any resource?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 48 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-KtwWgO_XNAAflor0MSa:-KtwZzhszARcW3XJrAwg:b-b1p8ds) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L48)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

should we avoid the case of searching for an UUID with no correspondence to any resource?
</blockquote></details>

only to avoid an else in the end? Because I don't see how to avoid the IF tests, and if later if decided to support another type o chassis we have to update the filter and the IF, the way it is we only need to update the IF.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 62 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-Ktw_QHGppJ3qMjDnBeA:-Ktw_QHGppJ3qMjDnBeB:b-qqtid9) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L62)):*
> ```Python
>             abort(500)
>         else:
>             abort(404)
> ```

Daniel, this will not work. the flask abort will raise an exception inside the try and will fall under your general exception and will raise a 500 error. In solution with your logic would be raise a HPOoneViewExecpton("Chassis type unknown") to be treated as 404 on your execption as a 404

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 56 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-KtwaDudNbggqrKo-pZp:-KtwaDudNbggqrKo-pZq:b-8c7bk8) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L56)):*
> ```Python
>             # ov_encl = ov_client.enclosures.get(uuid)
>             # ch = Chassis(ov_encl)
>             abort(500)
> ```

Although I suggested you to do this know that its now working as expected. Its giving the expected result as a collateral effect.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by danielreed** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 48 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-KtwWgO_XNAAflor0MSa:-Ktwa-YOkV5is5-9w672:b2sh4d8) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L48)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

only to avoid an else in the end? Because I don't see how to avoid the IF tests, and if later if decided to support another type o chassis we have to update the filter and the IF, the way it is we only need to update the IF.
</blockquote></details>

I think in that case the call returns an empty list [].  I guess we should probably add some checks here.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 56 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-KtwaDudNbggqrKo-pZp:-KtwdnQwM8mKqWnwbBmA:b8zbx9w) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L56)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

Although I suggested you to do this know that its now working as expected. Its giving the expected result as a collateral effect.
</blockquote></details>

Check my comment below, what do you think?

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 60 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-KtwaTOQFUZ7T3QAsiBR:-KtwdjCSbjQbHRJb-dPJ:b8zbx9w) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L60)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

same as above here
</blockquote></details>

Check my comment below, what do you think?

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 62 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-Ktw_QHGppJ3qMjDnBeA:-KtwdaoKEfOW-wWIk97o:bc5ygqv) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L62)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

Daniel, this will not work. the flask abort will raise an exception inside the try and will fall under your general exception and will raise a 500 error. In solution with your logic would be raise a HPOoneViewExecpton("Chassis type unknown") to be treated as 404 on your execption as a 404
</blockquote></details>

This seems to work: 
raise errors.OneViewRedfishError(
     'Chassis type not found'
)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 62 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-Ktw_QHGppJ3qMjDnBeA:-Ktwj_jW-tmueQZfMEOx:b-ftvy36) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L62)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

This seems to work: 
raise errors.OneViewRedfishError(
     'Chassis type not found'
)
</blockquote></details>

Actually you need to fake a HPOneViewExecption because of how you treat exception. This will fall in the 500 Error, unless you add and Except OneViewRedfishError to your execption list

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by ricardoas** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 48 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-KtwWgO_XNAAflor0MSa:-KtwvIplCOcjujN_kkvQ:b-yii8uu) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L48)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

I think in that case the call returns an empty list [].  I guess we should probably add some checks here.
</blockquote></details>

I was sure pointing in the empty list direction...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by ffdarkpenguin** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by ffdarkpenguin** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-:-KtxAHJWfgWzhEiG-4sr:bnfp4nl)*

**Comment by llvieira** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Comment by ricardoas** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-:-KtxSEpqDq45r23zKvd4:bnfp4nl)*

**Comment by ricardoas** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 48 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51#-KtwWgO_XNAAflor0MSa:-KtxSblN9LF2aCTm_sSj:b32w0x) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/87e58600ee7c5a297e5c35f945674201c13b049a/oneview_redfish_toolkit/blueprints/chassis.py#L48)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

I was sure pointing in the empty list direction...
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/51)*

**Pull request merged**
