### PR TITLE
Implement ComputerSystemCollection and Refactoring

### LINKED ISSUE #20: Implement ComputerSystemCollection
As oneview-redfish-toolkit user, I access "/redfish/v1/Systems" and receive info from available ComputerSystems in the OneView. The referenced ComputerSystem resources should point to a URL in the format "/redfish/v1/Systems/<server_hardware_uuid>".

### LINKED ISSUE #33: Refactoring #1
After discussing current implementation we agreed on some improvements.

### PR DESCRIPTION
**Pull request by llvieira**
Closes #20 
Closes #33 

This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/32)

### CODE REVIEW

**Comment by llvieira** [comment]
Closes #20

**Comment by danielreed** [comment]
Review status: 0 of 27 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/util.py, line 29 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KssuPyRCcZVXPLlOLA7:-KssuPyRCcZVXPLlOLA8:b-x4v3m7) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L29)):*
> ```Python
>     """Loads ini file
> 
>         Loads and parser the system ini file into config global var
> ```

Loads and parses, instead of Loads and parser

---

*[oneview_redfish_toolkit/util.py, line 30 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KssuWtr6oYdiLdkE-2P:-KssuWtr6oYdiLdkE-2Q:bgmpn8c) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L30)):*
> ```Python
> 
>         Loads and parser the system ini file into config global var
>         Loads json schemas intro schemas_dict global var
> ```

into instead of intro

---

*[oneview_redfish_toolkit/util.py, line 86 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswNLdnjayQCYAMpPF:-KsswNLdnjayQCYAMpPG:b-m6u2l7) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L86)):*
> ```Python
>     """Loads ini file
> 
>         Loads and parses the module ini file
> ```

parses

---

*[oneview_redfish_toolkit/util.py, line 158 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswY-qQcAfLQ3K7Fb8:-KsswY-qQcAfLQ3K7Fb9:bynkgwz) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L158)):*
> ```Python
> 
> def get_oneview_client():
>     '''Establishes a OneView connction to be used in the module
> ```

connection

---

*[oneview_redfish_toolkit/util.py, line 186 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswnsilEFSIvM26KWb:-KsswnsilEFSIvM26KWc:byflvt1) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L186)):*
> Reautenticou
Re-authenticated?

---

*[oneview_redfish_toolkit/api/errors.py, line 18 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswxyNFmTmZa-fqN1K:-KsswxyNFmTmZa-fqN1L:bz1y8sv) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/errors.py#L18)):*
> ```Python
> 
> 
> class OneViewRedfishError(Exception):
> ```

Would a simpler name be better here? Like just OneView error? Do we need Redfish in the name?

---

*[oneview_redfish_toolkit/api/errors.py, line 24 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KssxiI1XDRH2KVc76Ot:-KssxiI1XDRH2KVc76Ou:b-ovzb1s) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/errors.py#L24)):*
> ```Python
> 
> 
> class OneViewRedfishResourceNotFoundError(OneViewRedfishError):
> ```

Would a simpler name be better here? Like just OneViewResourceNotFoundError error? Do we need Redfish in the name?

---

*[oneview_redfish_toolkit/api/errors.py, line 30 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KssxpLknC5_SNTnU699:-KssxpLknC5_SNTnU69A:b5n5hmq) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/errors.py#L30)):*
> ```Python
> 
> 
> class OneViewRedfishResourceNotAccessibleError(OneViewRedfishError):
> ```

Would a simpler name be better here? Like just OneViewResourceNotAccessibleError error? Do we need Redfish in the name?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32)*

**Comment by ricardoas** [comment]
Reviewed 16 of 28 files at r1, 17 of 17 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/util.py, line 103 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-Kst4iOJY1zRzCQCqBkA:-Kst4iOJY1zRzCQCqBkB:bcyd3ob) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L103)):*
> ```Python
> 
>     config = configparser.ConfigParser()
>     config.optionxform = str
> ```

For my curiosity sake, what's this for?

---

*[oneview_redfish_toolkit/util.py, line 186 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswnsilEFSIvM26KWb:-Kst4vlB9Xrp4oMiVfdy:bb77uci) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L186)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

> Reautenticou
Re-authenticated?
</blockquote></details>

Yep!

---

*[oneview_redfish_toolkit/api/computer_system_collection.py, line 41 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-Kst59vhUHa1z9pyMwr8:-Kst59vhUHa1z9pyMwr9:bqkwnj5) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/computer_system_collection.py#L41)):*
> ```Python
>                 server_hardware: A list of dicts of server hardware.
>         """
>         super().__init__(util.schemas_dict[self.SCHEMA_NAME])
> ```

We could improve it even further, by just passing the self.SCHEMA_NAME and leaving util stuff inside RedfishJsonValidator...

---

*[oneview_redfish_toolkit/api/errors.py, line 18 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswxyNFmTmZa-fqN1K:-Kst5NwclsSHbTK7uu2i:bpradou) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/errors.py#L18)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

Would a simpler name be better here? Like just OneView error? Do we need Redfish in the name?
</blockquote></details>

I guess is makes it easy for now not to mix toolkit raised exceptions with the ones repassed from python-hpOneView... (what's the name being raised there?)

Apart from that, I'm also not sure about python nomenclature for Exceptions... is "SomethingError" reserved for any specific kind of exception?

---

*[oneview_redfish_toolkit/api/redfish_json_validator.py, line 66 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-Kst6a1y53Jv2QEVGzOE:-Kst6a1y53Jv2QEVGzOF:b-pp6q7) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/redfish_json_validator.py#L66)):*
> ```Python
>         """
> 
>         try:
> ```

At service_root we are not testing for the return not even waiting for any exception. Should we remove this and leave just
``jsonschema.validate(self.redfish, self.schema_obj)`` without try/except or return True?

---

*[oneview_redfish_toolkit/api/redfish_json_validator.py, line 83 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-Kst84XCG1-TpHAvyQHG:-Kst84XCG1-TpHAvyQHH:bi9wm9q) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/redfish_json_validator.py#L83)):*
> ```Python
>         """
> 
>         if util.config['redfish']['indent_json']:
> ```

We could also have exported this to a global, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32)*

**Comment by ffdarkpenguin** [comment]
Review status: 21 of 27 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/util.py, line 103 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-Kst4iOJY1zRzCQCqBkA:-KstsFBRg_0yB2yxMd2J:bkl6e94) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L103)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

For my curiosity sake, what's this for?
</blockquote></details>

making sure the file exists. configparser does not give you an error if you try to read a file that does not exists.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32)*

**Comment by ffdarkpenguin** [comment]
Review status: 21 of 27 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/api/errors.py, line 18 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswxyNFmTmZa-fqN1K:-KstuB-MFA3DzJ4RqDBV:bi9dna4) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/errors.py#L18)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

I guess is makes it easy for now not to mix toolkit raised exceptions with the ones repassed from python-hpOneView... (what's the name being raised there?)

Apart from that, I'm also not sure about python nomenclature for Exceptions... is "SomethingError" reserved for any specific kind of exception?
</blockquote></details>

I think plain OneViewError may be confusing with oneview.  I was thinking aboure renaming the file to OneViewRedfishError or OneviewRedfishException and make smaller names insed note prefixing everything with OneViewRedfish.
@ricardo we can use any name. Many tutorials use the term "Error" but if you prefer Exception let me know.

---

*[oneview_redfish_toolkit/api/errors.py, line 24 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KssxiI1XDRH2KVc76Ot:-KstuaqgYQi8LZXoRc1G:b-axrmq4) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/errors.py#L24)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

Would a simpler name be better here? Like just OneViewResourceNotFoundError error? Do we need Redfish in the name?
</blockquote></details>

see coments above

---

*[oneview_redfish_toolkit/api/errors.py, line 30 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KssxpLknC5_SNTnU699:-KstuoxzOjsEuDxs0lxw:bv0xzxm) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/errors.py#L30)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

Would a simpler name be better here? Like just OneViewResourceNotAccessibleError error? Do we need Redfish in the name?
</blockquote></details>

see coment on the first one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32)*

**Comment by ffdarkpenguin** [comment]
Review status: 21 of 27 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/api/redfish_json_validator.py, line 66 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-Kst6a1y53Jv2QEVGzOE:-KstuzduJ9r68rb_g2Iy:b58xnj1) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/redfish_json_validator.py#L66)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

At service_root we are not testing for the return not even waiting for any exception. Should we remove this and leave just
``jsonschema.validate(self.redfish, self.schema_obj)`` without try/except or return True?
</blockquote></details>

Now it returns None and we only treat exceptions. I dont think we should change this behavior just for service root.

---

*[oneview_redfish_toolkit/api/redfish_json_validator.py, line 83 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-Kst84XCG1-TpHAvyQHG:-KstvernUwazXHwpN4Dg:brkzv6f) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/redfish_json_validator.py#L83)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

We could also have exported this to a global, right?
</blockquote></details>

we exported config which have all configuration, so  yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32)*

**Comment by ricardoas** [comment]
:lgtm:

---

Reviewed 3 of 28 files at r1, 5 of 6 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/api/errors.py, line 18 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswxyNFmTmZa-fqN1K:-KsxSMkGlu2bfPa3iNYD:b-wnk82s) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/errors.py#L18)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

I think plain OneViewError may be confusing with oneview.  I was thinking aboure renaming the file to OneViewRedfishError or OneviewRedfishException and make smaller names insed note prefixing everything with OneViewRedfish.
@ricardo we can use any name. Many tutorials use the term "Error" but if you prefer Exception let me know.
</blockquote></details>

It's ok... I was just checking! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-:-KsxS4Mn2UIzdWyXSEVN:bnfp4nl)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/util.py, line 29 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KssuPyRCcZVXPLlOLA7:-KsxcbBfjXIl9c3uVDKO:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L29)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

Loads and parses, instead of Loads and parser
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/util.py, line 30 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KssuWtr6oYdiLdkE-2P:-KsxccT9HlP24zWiRq9i:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L30)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

into instead of intro
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/util.py, line 86 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswNLdnjayQCYAMpPF:-Ksxcdtaq9N-jWu1rsbg:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L86)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

parses
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/util.py, line 158 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-KsswY-qQcAfLQ3K7Fb8:-KsxceZpq_Hi1_RlyESa:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/util.py#L158)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

connection
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/api/computer_system_collection.py, line 41 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32#-Kst59vhUHa1z9pyMwr8:-KsxciBSVDsn9rZFOcs3:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/33fe4a0b0d9be3eb43023aea054783d8a52397ec/oneview_redfish_toolkit/api/computer_system_collection.py#L41)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

We could improve it even further, by just passing the self.SCHEMA_NAME and leaving util stuff inside RedfishJsonValidator...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/32)*

**Pull request merged**
