### PR TITLE
Implement a Flask receiver 

### LINKED ISSUE #15: Implement a Flask receiver
As oneview-redfish-toolkit user, I launch a flash service in a given port that answers a hellow world request. An equivalent test show be provided verifying the return code and content.

### PR DESCRIPTION
**Pull request by llvieira**
Closes #15

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/25)

### CODE REVIEW

**Comment by bsoutham** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25)*

**Comment by bsoutham** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-:-KrqbFjAb7mSUTPOm05d:bnfp4nl)*

**Comment by ricardoas** [comment]
I think it need some work before merging it...

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[oneview_redfish_toolkit/api/hello_world_api.py, line 21 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks4A-LH7Cxk44OfE-nJ:-Ks4A-LH7Cxk44OfE-nK:bd8kyb0) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f45170e787c606580fdb9bd18f2c47e12da531ae/oneview_redfish_toolkit/api/hello_world_api.py#L21)):*
> ```Python
> from flask import make_response
> 
> bp_hello_world_api = Blueprint("hello_world_api", __name__,
> ```

Should we rename it to a more significant name? maybe redfish_base? What will be the next blueprints? computing_server_api, chassis_api?

---

*[oneview_redfish_toolkit/api/hello_world_api.py, line 26 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks4BPVouXZktN5Sweud:-Ks4BPVouXZktN5Sweue:b-kqklx9) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f45170e787c606580fdb9bd18f2c47e12da531ae/oneview_redfish_toolkit/api/hello_world_api.py#L26)):*
> ```Python
> 
> @bp_hello_world_api.route("/", methods=["GET"])
> def list_server_hardware():
> ```

Definitely not a list_server_hardware function...

---

*[oneview_redfish_toolkit/api/hello_world_api.py, line 32 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks4BTn22imR3jeIVRdb:-Ks4BTn22imR3jeIVRdc:bmpg3b9) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f45170e787c606580fdb9bd18f2c47e12da531ae/oneview_redfish_toolkit/api/hello_world_api.py#L32)):*
> ```Python
>     :rtype: JSON
>     """
>     return make_response(jsonify({"v1": "/redfish/v1/"}), 200)
> ```

are there status code constants you can import on flask instead of hard-coding 200?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-:-Ks4Bw0CO8sYcy0e8L5x:b-ook2qv)*

**Comment by llvieira** [comment]
Completed changes!

For the status code we can use the Flask Status that include a set of constants representing it.

List of Flask Status code: [http://www.flaskapi.org/api-guide/status-codes/](http://www.flaskapi.org/api-guide/status-codes/)

**Comment by ricardoas** [comment]
Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[oneview_redfish_toolkit/api/redfish_base_api.py, line 22 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks56yWCTQ3IomWQ6CTw:-Ks56yWDUKAHQPK16wuv:b1gwo16) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/3ec13431df2060ae654e22a313403f9ec5a6b90b/oneview_redfish_toolkit/api/redfish_base_api.py#L22)):*
> ```Python
> from flask_api import status
> 
> redfish_base = Blueprint("hello_world_api", __name__, url_prefix="/redfish")
> ```

nit: "hello_world_api"

---

*[oneview_redfish_toolkit/tests/test_redfish_base_api.py, line 51 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks572p4OBatgaDE1XoJ:-Ks572p4OBatgaDE1XoK:bxav7so) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/3ec13431df2060ae654e22a313403f9ec5a6b90b/oneview_redfish_toolkit/tests/test_redfish_base_api.py#L51)):*
> ```Python
>         self.assertEqual(result.status_code, status.HTTP_200_OK)
> 
>     def test_response_hello_world(self):
> ```

test_get_redfish_base??

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25)*

**Comment by llvieira** [comment]
Updated!

**Comment by ricardoas** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-:-Ks5TzTXGqwiU0_hSdXR:bnfp4nl)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[oneview_redfish_toolkit/api/redfish_base_api.py, line 21 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks4A-LH7Cxk44OfE-nJ:-Ks5VNMByAJCK0WNs-Zz:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f45170e787c606580fdb9bd18f2c47e12da531ae/oneview_redfish_toolkit/api/redfish_base_api.py#L21)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

Should we rename it to a more significant name? maybe redfish_base? What will be the next blueprints? computing_server_api, chassis_api?
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/api/redfish_base_api.py, line 26 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks4BPVouXZktN5Sweud:-Ks5VSbgRUhGum3PHOw0:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f45170e787c606580fdb9bd18f2c47e12da531ae/oneview_redfish_toolkit/api/redfish_base_api.py#L26)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

Definitely not a list_server_hardware function...
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/api/redfish_base_api.py, line 32 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks4BTn22imR3jeIVRdb:-Ks5VUYCqGgqsc72_RXU:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f45170e787c606580fdb9bd18f2c47e12da531ae/oneview_redfish_toolkit/api/redfish_base_api.py#L32)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

are there status code constants you can import on flask instead of hard-coding 200?
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/api/redfish_base_api.py, line 22 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks56yWCTQ3IomWQ6CTw:-Ks5VREZ3KQWW4NOoyEd:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/3ec13431df2060ae654e22a313403f9ec5a6b90b/oneview_redfish_toolkit/api/redfish_base_api.py#L22)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

nit: "hello_world_api"
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/tests/test_redfish_base_api.py, line 51 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25#-Ks572p4OBatgaDE1XoJ:-Ks5VXyO9QMoubpfwn58:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/3ec13431df2060ae654e22a313403f9ec5a6b90b/oneview_redfish_toolkit/tests/test_redfish_base_api.py#L51)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

test_get_redfish_base??
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/25)*

**Pull request merged**
