### PR TITLE
Remove unnecessary dependencies generated by cookiecutter

### PR DESCRIPTION
**Pull request by llvieira**
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/26)

### CODE REVIEW

**Comment by ricardoas** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test-requirements.txt, line 9 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/26#-Ks4CTwIzqhWnNaYqoii:-Ks4CTwIzqhWnNaYqoij:b-qupgv0) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f45170e787c606580fdb9bd18f2c47e12da531ae/test-requirements.txt#L9)):*
> ```
> coverage>=4.0,!=4.4 # Apache-2.0
> python-subunit>=0.0.18 # Apache-2.0/BSD
> sphinx>=1.6.2 # BSD
> ```

Do we need this to generate docs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/26#-:-Ks4DeEh-e7pX5xzbhN2:bnfp4nl)*

**Comment by llvieira** [comment]
@ricardoas To generate documentation the dependencies are in the **tox.ini** file. We do not need this.

**Comment by llvieira** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test-requirements.txt, line 9 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/26#-Ks4CTwIzqhWnNaYqoii:-Ks5WtaPc_J3p8n9R8rq:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f45170e787c606580fdb9bd18f2c47e12da531ae/test-requirements.txt#L9)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

Do we need this to generate docs?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/26)*

**Comment by ricardoas** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/26#-:-Ks5WgtGQfuEWYO9Z3jO:bnfp4nl)*

**Pull request merged**
