### PR TITLE
Added util.py with load_config and load_schemas function.

### LINKED ISSUE #16: Implement a schema loader
As a dev, I access a class with pre-loaded schema for each redfish structure according to properties specified in a configuration file. The user should be able to specify the folder and the JSON file for each of these structures.

### PR DESCRIPTION
**Pull request by ffdarkpenguin**
Created util.py with load_config and load_schemas function
Added schemas dir with all json schemas from DPS8010_2017.1.zip files. 
Added unit tests for both functions
Closes #16 

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/28)

### CODE REVIEW

**Comment by danielreed** [comment]
Review status: 0 of 237 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsAIv4e7N6g1PxJDQsI:-KsAIv4e7N6g1PxJDQsJ:b-b6n2q7) (no related file):*
Just a question: why are we loading all of the Redfish schemas when we probably won't need more than half of them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ffdarkpenguin** [comment]
Closes #17

**Comment by ffdarkpenguin** [comment]
@danielreed I consulted @ricardoas and he recommended putting all at once. I asked him to talk to you about it. If you decided to remove them just let me know.

**Comment by ricardoas** [comment]
@danielreed i asked them to push with the whole bundle of JSONSs just in case... in fact I guess that the ones that are really being loaded when the service starts are the ones at redfish.ini right?

```
[schemas]
  ServiceRoot = ServiceRoot.v1_2_0.json
  ChassisCollection = ChassisCollection.json
  Chassis = Chassis.v1_5_0.json
  ComputerSystemCollection = ComputerSystemCollection.json
  ComputerSystem = ComputerSystem.v1_4_0.json
  ManagerCollecion = ManagerCollection.json
  Manager = Manager.v1_3_1.json
  EventService = EventService.v1_0_4.json
  EventEestination = EventDestination.v1_2_0.json
  Event = Event.v1_2_0.json 
```

**Comment by ffdarkpenguin** [comment]
Yes, for now, this where the ones I thing we going to need. In fact we use others, that are referred in the json files. But at resolv time they go to DMTF website and grab the referring file.

**Comment by ricardoas** [comment]
then, is it ok to maitain only these 10 json at our repo?

---

Reviewed 237 of 237 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsAIv4e7N6g1PxJDQsI:-KsJb9FWA6PVT4CnMj5H:b-l4ig86) (no related file):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

Just a question: why are we loading all of the Redfish schemas when we probably won't need more than half of them?
</blockquote></details>

should we delete them and leave only the ones being used right now and add them on demand?

---

*[.bashrc, line 1 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJZjzwJJPN8swG3JRX:-KsJZjzwJJPN8swG3JRY:b74in76) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/.bashrc#L1)):*
> ```Shell
> [[ -s "$HOME/.pythonbrew/etc/bashrc" ]] && source "$HOME/.pythonbrew/etc/bashrc"
> ```

This should not be committed...

---

*[oneview_redfish_toolkit/redfish.ini, line 6 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_6w2TC8fVZ74cFrW:-KsJ_6w2TC8fVZ74cFrX:bwvi96i) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/redfish.ini#L6)):*
> ```INI
> 
> [oneview_config]
> ip =  
> ```

placeholders?

---

*[oneview_redfish_toolkit/util.py, line 19 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_I75BJiBeMITimHb:-KsJ_I75BJiBeMITimHc:b-ql8wyb) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L19)):*
> ```Python
> 
> import collections
> import configparser
> ```

We did removed this from requirements.txt, I guess we should bring it back now...

---

*[oneview_redfish_toolkit/util.py, line 33 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_mQ7NoJSA3l0snhy:-KsJ_mQ7NoJSA3l0snhz:b-nwa5bf) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L33)):*
> ```Python
> 
>         Returns:
>             If fails: print a error message and returns False
> ```

why false, are we testing against it anywhere?
The whole application should fail if we cannot load a config, if we return None here and in the main file test
if config:
    do_something_with_the_config(config)
than we'll be ok, right?

---

*[oneview_redfish_toolkit/util.py, line 62 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_j-rQSfIyboVSm3W:-KsJ_j-rQSfIyboVSm3X:bwhf82d) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L62)):*
> ```Python
> 
>         Returns:
>             If fails: print a error message and returns False
> ```

why false? are we checking against it anywhere?

---

*[oneview_redfish_toolkit/util.py, line 67 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_WeQ1xu_L1ud-d4Y:-KsJ_WeQ1xu_L1ud-d4Z:bvnxthn) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L67)):*
> ```Python
>     """
> 
>     if os.path.isdir(schema_dir) is False:
> ```

if not os.path.isdir(schema_dir)

---

*[oneview_redfish_toolkit/util.py, line 70 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_bCcSQ_bSoe_vGpw:-KsJ_bCcSQ_bSoe_vGpx:bnj7hl0) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L70)):*
> ```Python
>         print("Schema dir is not a valid dir: {}".format(schema_dir))
>         return False
>     if os.access(schema_dir, os.R_OK) is False:
> ```

same as above

---

*[oneview_redfish_toolkit/util.py, line 85 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_x899-UJBR_O_LVN:-KsJ_x899-UJBR_O_LVO:b-mchm1z) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L85)):*
> ```Python
> 
> 
> if __name__ == '__main__':
> ```

do we need this?

---

*[oneview_redfish_toolkit/tests/test_util_load_config.py, line 85 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJb7AeZ2K0jMrIK9ob:-KsJb7AeZ2K0jMrIK9oc:b176d0q) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/tests/test_util_load_config.py#L85)):*
> ```Python
>                         self.config_file))
> 
> if __name__ == '__main__':
> ```

same as the other test

---

*[oneview_redfish_toolkit/tests/test_util_load_schemas.py, line 58 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJagcZXOaT3X4_jJRs:-KsJagcZXOaT3X4_jJRt:bf1bafm) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/tests/test_util_load_schemas.py#L58)):*
> ```Python
> 
> 
> if __name__ == '__main__':
> ```

tox needs this? i think we can run individual tests using "tox -epy35 -- full_test_path"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-:-KsJbdZpOR4GLrMm3y37:b-yknut7)*

**Comment by ricardoas** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[oneview_redfish_toolkit/util.py, line 45 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJcVAJMgi_jj9k_9uH:-KsJcVAJMgi_jj9k_9uI:b-dp2swv) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L45)):*
> ```Python
>         config.read(ini_file)
>     except Exception as e:
>         print(e)
> ```

should we start with logging from scratch instead of printing? does flask uses python default log lib?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by danielreed** [comment]
These 10 schemas will probably also depend on other schemas via the $ref.  But I agree that it would be nice to limit things to just the schemas that we need, though it might be time consuming to figure that out.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[oneview_redfish_toolkit/util.py, line 45 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJcVAJMgi_jj9k_9uH:-KsJjTDzBs2TWJWTfHa_:bm57c8d) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L45)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

should we start with logging from scratch instead of printing? does flask uses python default log lib?
</blockquote></details>

I think we should use the flask logger:  app.logger

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-:-KsJk-3fLgbYvIqarTCu:b-bv48pt)*

**Comment by llvieira** [comment]
Reviewed 237 of 237 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[oneview_redfish_toolkit/tests/test_util_load_schemas.py, line 58 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJagcZXOaT3X4_jJRs:-KsK5DQkEbgy51fZqQJC:bifueay) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/tests/test_util_load_schemas.py#L58)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

tox needs this? i think we can run individual tests using "tox -epy35 -- full_test_path"
</blockquote></details>

Tox doesn't need this. Using what Ricardo says it's enough to run a single test class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ffdarkpenguin** [comment]
This was fixed, we  only have necessary files now.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-:-KsKisUK1zqOob5qyCCn:b-wxry7i)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[.bashrc, line 1 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJZjzwJJPN8swG3JRX:-KsKjOUviWeNEQkbP570:br2wci9) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/.bashrc#L1)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

This should not be committed...
</blockquote></details>

This is removed in the next PR, please ignore for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[.bashrc, line 1 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJZjzwJJPN8swG3JRX:-KsKjUP0rjF1KAq4arOt:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/.bashrc#L1)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

This is removed in the next PR, please ignore for now.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[oneview_redfish_toolkit/redfish.ini, line 6 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_6w2TC8fVZ74cFrW:-KsKjXv5iCYxJ6Roztu0:b2nign6) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/redfish.ini#L6)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

placeholders?
</blockquote></details>

yes

---

*[oneview_redfish_toolkit/util.py, line 19 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_I75BJiBeMITimHb:-KsKjdbpm4el4CuiB8KT:bgqf38u) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L19)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

We did removed this from requirements.txt, I guess we should bring it back now...
</blockquote></details>

inserted on requirements

---

*[oneview_redfish_toolkit/util.py, line 45 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJcVAJMgi_jj9k_9uH:-KsKjoqs1ucoz-YIbtfy:btedcz) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L45)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

I think we should use the flask logger:  app.logger
</blockquote></details>

will be postponed to a later fix

---

*[oneview_redfish_toolkit/util.py, line 67 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_WeQ1xu_L1ud-d4Y:-KsKk0bxn0Hne1zNZ6Ef:b5lx6bc) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L67)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

if not os.path.isdir(schema_dir)
</blockquote></details>

IMHO the previous form is clearer.

---

*[oneview_redfish_toolkit/util.py, line 70 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_bCcSQ_bSoe_vGpw:-KsKk8XSeMQE6-Up66p7:bnj7hl0) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L70)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

same as above

---

*[oneview_redfish_toolkit/util.py, line 85 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_x899-UJBR_O_LVN:-KsKkBH0JaXEsJJJ8h1U:b-hfpv0l) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L85)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

do we need this?
</blockquote></details>

removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[oneview_redfish_toolkit/tests/test_util_load_config.py, line 85 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJb7AeZ2K0jMrIK9ob:-KsKkGPCshVqs-4dsLwl:b-hfpv0l) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/tests/test_util_load_config.py#L85)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

same as the other test
</blockquote></details>

removed

---

*[oneview_redfish_toolkit/tests/test_util_load_schemas.py, line 58 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJagcZXOaT3X4_jJRs:-KsKkJDLJ1DMVxj9G4OO:b-hfpv0l) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/tests/test_util_load_schemas.py#L58)):*
<details><summary><i>Previously, llvieira (Lucas Lima Vieira) wrote…</i></summary><blockquote>

Tox doesn't need this. Using what Ricardo says it's enough to run a single test class.
</blockquote></details>

removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[oneview_redfish_toolkit/util.py, line 62 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_j-rQSfIyboVSm3W:-KsKl4ocRqTmwDlGW1JF:bj5mep6) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L62)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

why false? are we checking against it anywhere?
</blockquote></details>

no reason. If you want none I ll do it. And will add the check

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[oneview_redfish_toolkit/util.py, line 33 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_mQ7NoJSA3l0snhy:-KsKlIXpJk8qxq_YgY33:bvhyn7x) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L33)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

why false, are we testing against it anywhere?
The whole application should fail if we cannot load a config, if we return None here and in the main file test
if config:
    do_something_with_the_config(config)
than we'll be ok, right?
</blockquote></details>

no reason if you want none I ll do that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[oneview_redfish_toolkit/util.py, line 45 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJcVAJMgi_jj9k_9uH:-KsKlVSg7h5c2ULlV15R:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L45)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

will be postponed to a later fix
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/util.py, line 67 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_WeQ1xu_L1ud-d4Y:-KsKl_4dqF9gGEN48Vr_:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L67)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

IMHO the previous form is clearer.
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/util.py, line 70 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_bCcSQ_bSoe_vGpw:-KsKlaUDb-1heajdOgDn:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L70)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/util.py, line 85 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJ_x899-UJBR_O_LVN:-KsKlbcg0nOO9w304Ogw:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/util.py#L85)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

removed
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/tests/test_util_load_config.py, line 85 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJb7AeZ2K0jMrIK9ob:-KsKlcXbjPfJoYLUaXhH:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/tests/test_util_load_config.py#L85)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

removed
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/tests/test_util_load_schemas.py, line 58 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsJagcZXOaT3X4_jJRs:-KsKldC3u0FGX96EoiJk:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/f128571e77acc13001faf3f2ef9b85313ebb8c9d/oneview_redfish_toolkit/tests/test_util_load_schemas.py#L58)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

removed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-KsAIv4e7N6g1PxJDQsI:-KsKnJ39DIyoR2j16DSS:bb7f2mf) (no related file):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

should we delete them and leave only the ones being used right now and add them on demand?
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28)*

**Comment by ricardoas** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-:-KsK0CllDgh7c-MSRjHu:bnfp4nl)*

**Comment by llvieira** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/28#-:-KsKqTF8o9Mjr9uJEydF:bnfp4nl)*

**Pull request merged**
