### PR TITLE
Fix IndicatorLED field on Blade Chassis

### LINKED ISSUE #62: Fix IndicatorLED field on Blade Chassis
As oneview-redfish-toolkit, I access "/redfish/v1/Chassis/<server_hardware_uuid>" and receive basic information of the server hardware chassis containing IndicatorLED field properly filled.

### PR DESCRIPTION
**Pull request by llvieira**
Closes #62

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/63)

### CODE REVIEW

**Comment by ffdarkpenguin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[oneview_redfish_toolkit/api/chassis.py, line 66 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63#-Ku0vV1IqaLaLa3-z-iZ:-Ku0vV1IqaLaLa3-z-i_:bduww3p) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/1e0bda236c78f26f0a000b74baa387bf7a846eb9/oneview_redfish_toolkit/api/chassis.py#L66)):*
> ```Python
>         self._validate()
> 
>     def _map_indicator_led(self, uid_state):
> ```

please do issue #53 before this issue so you don't duplicate code

---

*[oneview_redfish_toolkit/api/chassis.py, line 86 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63#-Ku0vUCj9hUpvWnBHkni:-Ku0vUCksoAKAdJLospD:b-1lfv59) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/1e0bda236c78f26f0a000b74baa387bf7a846eb9/oneview_redfish_toolkit/api/chassis.py#L86)):*
>     def _map_indicator_led(self, uid_state):
>         """Maps Oneview's uid state to Redfish's indicator led.
>  
>             Maps the known OneView uid state to Redfish indicator led.
>             If a unknown uid state shows up it will be mapped to Unknown.
>  
>             Args:
>                 uid_state: Uid state of Oneview.
>  
>             Returns:
>                 string: Redfish indicator led.
>         """
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         redfish_oneview_indicator_led_map = dict()
>         redfish_oneview_indicator_led_map["On"] = "Lit"
>         redfish_oneview_indicator_led_map["Off"] = "Off"
>         redfish_oneview_indicator_led_map["Blink"] = "Blinking"
</details>
>  
>         try:
>             return redfish_oneview_indicator_led_map[uid_state]
>         except Exception:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63)*

**Comment by llvieira** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[oneview_redfish_toolkit/api/chassis.py, line 66 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63#-Ku0vV1IqaLaLa3-z-iZ:-Ku1-SJ2N-UmdZjWzNs4:b-837i48) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/1e0bda236c78f26f0a000b74baa387bf7a846eb9/oneview_redfish_toolkit/api/chassis.py#L66)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

please do issue #53 before this issue so you don't duplicate code
</blockquote></details>

Okay!

---

*[oneview_redfish_toolkit/api/chassis.py, line 86 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63#-Ku0vUCj9hUpvWnBHkni:-Ku1-XRLMm97VrJSqcMJ:b2nh8oq) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/1e0bda236c78f26f0a000b74baa387bf7a846eb9/oneview_redfish_toolkit/api/chassis.py#L86)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

>     def _map_indicator_led(self, uid_state):
>         """Maps Oneview's uid state to Redfish's indicator led.
>  
>             Maps the known OneView uid state to Redfish indicator led.
>             If a unknown uid state shows up it will be mapped to Unknown.
>  
>             Args:
>                 uid_state: Uid state of Oneview.
>  
>             Returns:
>                 string: Redfish indicator led.
>         """
>  
>         redfish_oneview_indicator_led_map = dict()
>         redfish_oneview_indicator_led_map["On"] = "Lit"
>         redfish_oneview_indicator_led_map["Off"] = "Off"
>         redfish_oneview_indicator_led_map["Blink"] = "Blinking"
>  
>         try:
>             return redfish_oneview_indicator_led_map[uid_state]
>         except Exception:

</blockquote></details>

???

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63)*

**Comment by ricardoas** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[oneview_redfish_toolkit/api/chassis.py, line 87 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63#-Ku5R6kAfqBf_Yw3oMVA:-Ku5R6kAfqBf_Yw3oMVB:b-tr4s16) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/1e0bda236c78f26f0a000b74baa387bf7a846eb9/oneview_redfish_toolkit/api/chassis.py#L87)):*
> ```Python
>             return redfish_oneview_indicator_led_map[uid_state]
>         except Exception:
>             return "Unknown"
> ```

Aren't people supposed to use None for "Unknown" state? I though I've seen that on a comment at the JSON schema...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/api/chassis.py, line 87 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63#-Ku5R6kAfqBf_Yw3oMVA:-Ku5SV1beeZMWNuFCG7E:b-8bacxp) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/1e0bda236c78f26f0a000b74baa387bf7a846eb9/oneview_redfish_toolkit/api/chassis.py#L87)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

Aren't people supposed to use None for "Unknown" state? I though I've seen that on a comment at the JSON schema...
</blockquote></details>

None is not used in JSON schemas, it's a Python keyword. Maybe null should be used instead of "Unknown".

On Chassis JSON schema, have the following: 

"IndicatorLED": {
            "type": "string",
            "enum": [
                "Unknown",
                "Lit",
                "Blinking",
                "Off"
            ],
            "enumDescriptions": {
                "Unknown": "The state of the Indicator LED cannot be determined.",
                "Lit": "The Indicator LED is lit.",
                "Blinking": "The Indicator LED is blinking.",
                "Off": "The Indicator LED is off."
            },
            "enumDeprecated": {
                "Unknown": "This value has been Deprecated in favor of returning null if the state is unknown."
            } 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63)*

**Comment by ricardoas** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/api/chassis.py, line 87 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63#-Ku5R6kAfqBf_Yw3oMVA:-Ku5XSzPmGumTp7HbwTi:bjq0o1j) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/1e0bda236c78f26f0a000b74baa387bf7a846eb9/oneview_redfish_toolkit/api/chassis.py#L87)):*
<details><summary><i>Previously, llvieira (Lucas Lima Vieira) wrote…</i></summary><blockquote>

None is not used in JSON schemas, it's a Python keyword. Maybe null should be used instead of "Unknown".

On Chassis JSON schema, have the following: 

"IndicatorLED": {
            "type": "string",
            "enum": [
                "Unknown",
                "Lit",
                "Blinking",
                "Off"
            ],
            "enumDescriptions": {
                "Unknown": "The state of the Indicator LED cannot be determined.",
                "Lit": "The Indicator LED is lit.",
                "Blinking": "The Indicator LED is blinking.",
                "Off": "The Indicator LED is off."
            },
            "enumDeprecated": {
                "Unknown": "This value has been Deprecated in favor of returning null if the state is unknown."
            } 
</blockquote></details>

yeah... I was relating to this "enumDeprecated" tag... null should be then. Does python json lib maps None to null?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/api/chassis.py, line 87 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63#-Ku5R6kAfqBf_Yw3oMVA:-Ku5Zr7EHYuOMPM8JenM:b-izof5a) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/1e0bda236c78f26f0a000b74baa387bf7a846eb9/oneview_redfish_toolkit/api/chassis.py#L87)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

yeah... I was relating to this "enumDeprecated" tag... null should be then. Does python json lib maps None to null?
</blockquote></details>

json.dumps(None) solve this issue... :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63)*

**Comment by llvieira** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/api/chassis.py, line 87 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63#-Ku5R6kAfqBf_Yw3oMVA:-Ku5aVfWxW5M99unGO-n:b-896fja) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/1e0bda236c78f26f0a000b74baa387bf7a846eb9/oneview_redfish_toolkit/api/chassis.py#L87)):*
<details><summary><i>Previously, llvieira (Lucas Lima Vieira) wrote…</i></summary><blockquote>

json.dumps(None) solve this issue... :)
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/63)*

**Comment by llvieira** [comment]
In fact this problem was solved on pull request #53

**Pull request closed without merging**
