### PR TITLE
Implement Enclosure Chassis

### LINKED ISSUE #38: Implement Enclosure Chassis
As oneview-redfish-toolkit, I access "/redfish/v1/Chassis/<enclosure_uuid>" and receive basic information of the enclosure's chassis and a link back to all ComputerSystem Chassis it contains.

### LINKED ISSUE #41: Add link to "OneView Rack" Chassis on Enclosure Chassis
As oneview-redfish-toolkit, I access "/redfish/v1/Chassis/<enclosure_uuid>" and the info returned contains a link to the OneView's Rack equivalent Chassis on the "ContainedBy" field.

### PR DESCRIPTION
**Pull request by llvieira**
Closes #38 
Closes #41

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/60)

### CODE REVIEW

**Comment by danielreed** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/60#-:-Ku0ShvwJQ-EQaxGmi85:bnfp4nl)*

**Comment by ffdarkpenguin** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/60#-:-Ku0i1A9Bd5d_zIahnK_:bnfp4nl)*

**Comment by ffdarkpenguin** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/60)*

**Comment by ricardoas** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/60#-:-Ku0mbtWMs7dn978Fu4P:bnfp4nl)*

**Pull request merged**
