### PR TITLE
Add "ContainedBy" link on BladeChassis and tests for blade

### LINKED ISSUE #40: Add link to "OneView Enclosure" Chassis on Blade Chassis
As oneview-redfish-toolkit, I access "/redfish/v1/System/<server_hardware_uuid>" and the info returned contains a link to the OneView's Enclosure equivalent Chassis on the "ContainedBy" field.

### LINKED ISSUE #61: Add tests to Blade Chassis case on blueprint

### PR DESCRIPTION
**Pull request by danielreed**
chassis blueprint.

Closes #61 and closes #40

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/64)

### CODE REVIEW

**Comment by ffdarkpenguin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[oneview_redfish_toolkit/api/chassis.py, line 62 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64#-Ku1GasPBiJ_NqeKsn28:-Ku1GasPBiJ_NqeKsn29:b-3ibw0h) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/822de27bd62fa4f80960a7522180d44bdfb7026e/oneview_redfish_toolkit/api/chassis.py#L62)):*
> ```Python
>         self.redfish["Links"]["ComputerSystems"][0]["@odata.id"] = \
>             "/redfish/v1/Systems/" + hardware['uuid']
>         if hardware["locationUri"] is not None:
> ```

Daniel is there any chance of a server hardware do not have a enclosure?!?
If no, no need to test,
If yes, what is the case? And in this case should we kick an error or just left ContainedBy blank like you did?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64)*

**Comment by danielreed** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[oneview_redfish_toolkit/api/chassis.py, line 62 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64#-Ku1GasPBiJ_NqeKsn28:-Ku1HQzFPHSyvKgb9hNJ:bn6ymuc) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/822de27bd62fa4f80960a7522180d44bdfb7026e/oneview_redfish_toolkit/api/chassis.py#L62)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

Daniel is there any chance of a server hardware do not have a enclosure?!?
If no, no need to test,
If yes, what is the case? And in this case should we kick an error or just left ContainedBy blank like you did?
</blockquote></details>

I believe only a DL/rack server would not have a locationUri.  I was just trying to be safe here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64)*

**Comment by ffdarkpenguin** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[oneview_redfish_toolkit/api/chassis.py, line 62 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64#-Ku1GasPBiJ_NqeKsn28:-Ku1I6lwO2K2KPSqCn9S:bereivm) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/822de27bd62fa4f80960a7522180d44bdfb7026e/oneview_redfish_toolkit/api/chassis.py#L62)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

I believe only a DL/rack server would not have a locationUri.  I was just trying to be safe here. 
</blockquote></details>

Ok, closing this debate on my part as we are only focusing on Enclosures only now. Agree with you about being safe, but I wonder if that´s  the correct response to that. Lets leave it for now as it should never be a issue to our goal. PO can review this if he wants to.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64)*

**Comment by ffdarkpenguin** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64#-:-Ku1JI2owHedCjAoNHAg:bnfp4nl)*

**Comment by llvieira** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64#-:-Ku1M4TQ6DA51iIxjzdu:bnfp4nl)*

**Comment by llvieira** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64)*

**Comment by ricardoas** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64#-:-Ku5TpxL1Gk3AdBpzrxL:bnfp4nl)*

**Comment by ffdarkpenguin** [comment]
Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64)*

**Comment by ricardoas** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/64#-:-KuQe-BzsXL4j7oCN9au:bnfp4nl)*

**Pull request merged**
