### PR TITLE
Refactor Chassis structures

### LINKED ISSUE #53: Refactor Chassis structures
As oneview-redfish-toolkit developer, I should maintain common behavior for all Chassis variants in a single place and still be able to code specific behavior.

### PR DESCRIPTION
**Pull request by llvieira**
Closes #53

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/65)

### CODE REVIEW

**Comment by ffdarkpenguin** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[oneview_redfish_toolkit/api/chassis.py, line 49 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1Lz-qfyZAXjYemoNY:-Ku1Lz-qfyZAXjYemoNZ:b-frhrlq) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/api/chassis.py#L49)):*
> ```Python
>         self.redfish["Name"] = oneview_resource["name"]
>         self.redfish["Manufacturer"] = "HPE"
>         self.redfish["SerialNumber"] = oneview_resource["serialNumber"]
> ```

rack have serial number? 

---

*[oneview_redfish_toolkit/api/chassis.py, line 50 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1M76reefWKio-ol52:-Ku1M76reefWKio-ol53:bmvm4m1) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/api/chassis.py#L50)):*
> ```Python
>         self.redfish["Manufacturer"] = "HPE"
>         self.redfish["SerialNumber"] = oneview_resource["serialNumber"]
>         self.redfish["IndicatorLED"] = self. \
> ```

rack have led indicator???

---

*[oneview_redfish_toolkit/api/enclosure_chassis.py, line 56 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1M__Ut92RV2rZftVs:-Ku1M__Ut92RV2rZftVt:b-2csa7v) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/api/enclosure_chassis.py#L56)):*
> ```Python
>         self.redfish["Links"]["ContainedBy"]["@odata.id"] = \
>             "/redfish/v1/Chassis/" + environmental_configuration["rackId"]
>         self.redfish["@odata.id"] = "/redfish/v1/Chassis/MultiBladeEncl"
> ```

???? makes no sense

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 29 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1MlT9EZFzm5dCtYll:-Ku1MlT9EZFzm5dCtYlm:bvxmn49) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/blueprints/chassis.py#L29)):*
> ```Python
> 
> # Own libs
> from hpOneView.exceptions import HPOneViewException
> ```

hponeview is 3rparty on this project not own lib

---

*[oneview_redfish_toolkit/mockups/BladeChassis.json, line 7 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1NDBVUXeuWXR_kEmp:-Ku1NDBVUXeuWXR_kEmq:bp67hju) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/mockups/BladeChassis.json#L7)):*
> ```JSON
>     "Manufacturer": "HPE",
>     "SerialNumber": "2M201136GR",
>     "IndicatorLED": "Off",
> ```

if rack don't support led chant it here too

---

*[oneview_redfish_toolkit/mockups/EnclosureChassis.json, line 7 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1NUEzHXB2rvEHRbUL:-Ku1NUF-mIz9Jl15VSGZ:b-ku0blq) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/mockups/EnclosureChassis.json#L7)):*
> ```JSON
>     "Manufacturer": "HPE",
>     "SerialNumber": "0000A66101",
>     "IndicatorLED": "Lit",
> ```

same case o rack led here

---

*[oneview_redfish_toolkit/tests/api/test_enclosure_chassis.py, line 45 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1Ng9AvlFMx2mmGIJ0:-Ku1Ng9BxMOd0eRx95i1:b-jucr8g) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/tests/api/test_enclosure_chassis.py#L45)):*
> ```Python
>         with open(
>                 'oneview_redfish_toolkit/mockups/'
>                 'EnvironmentalConfig.json'
> ```

should leave Enclosure on the name, Env config may apear for another piece. Fix other place if changed here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65)*

**Comment by llvieira** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[oneview_redfish_toolkit/api/chassis.py, line 49 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1Lz-qfyZAXjYemoNY:-Ku1PO2cxCU_Yrkxogq-:b-pu84yd) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/api/chassis.py#L49)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

rack have serial number? 
</blockquote></details>

Yes, the Rack OneView response have serial number.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65)*

**Comment by llvieira** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[oneview_redfish_toolkit/api/enclosure_chassis.py, line 56 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1M__Ut92RV2rZftVs:-Ku1PjerVCtrmbsQY7lZ:b-g3nvif) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/api/enclosure_chassis.py#L56)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

???? makes no sense
</blockquote></details>

Specifically, what make no senses? I do not understand very well...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65)*

**Comment by ffdarkpenguin** [comment]
Review status: 0 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[oneview_redfish_toolkit/api/enclosure_chassis.py, line 56 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1M__Ut92RV2rZftVs:-Ku1Y0XhySKAQR5lzXy7:bm1ymfs) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/api/enclosure_chassis.py#L56)):*
>  self.redfish["@odata.id"] = "/redfish/v1/Chassis/MultiBladeEncl"
this line makes no sense

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65)*

**Comment by ffdarkpenguin** [comment]
Review status: 0 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[oneview_redfish_toolkit/api/enclosure_chassis.py, line 56 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1M__Ut92RV2rZftVs:-Ku1YVDYh2ZBhyuz39lI:b-p4edv5) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/api/enclosure_chassis.py#L56)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

>  self.redfish["@odata.id"] = "/redfish/v1/Chassis/MultiBladeEncl"
this line makes no sense
</blockquote></details>

the entire line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65)*

**Comment by llvieira** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[oneview_redfish_toolkit/api/chassis.py, line 50 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1M76reefWKio-ol52:-Ku1yeL7UGjJbwStveNx:b-u53m7p) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/api/chassis.py#L50)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

rack have led indicator???
</blockquote></details>

No, I already changed it. Thanks

---

*[oneview_redfish_toolkit/api/enclosure_chassis.py, line 56 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1M__Ut92RV2rZftVs:-Ku1z88dLgFil8QM-ROu:bss4a2b) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/api/enclosure_chassis.py#L56)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

the entire line
</blockquote></details>

Removed.

---

*[oneview_redfish_toolkit/blueprints/chassis.py, line 29 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1MlT9EZFzm5dCtYll:-Ku1zCF9euUFO2lH9Wpx:b-9f1ic1) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/blueprints/chassis.py#L29)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

hponeview is 3rparty on this project not own lib
</blockquote></details>

Ok, changed.

---

*[oneview_redfish_toolkit/mockups/BladeChassis.json, line 7 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1NDBVUXeuWXR_kEmp:-Ku1zHA1tHaeDrhWIIhQ:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/mockups/BladeChassis.json#L7)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

if rack don't support led chant it here too
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/mockups/EnclosureChassis.json, line 7 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1NUEzHXB2rvEHRbUL:-Ku1zLX1T9JPc-h7jpcm:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/mockups/EnclosureChassis.json#L7)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

same case o rack led here
</blockquote></details>

Done.

---

*[oneview_redfish_toolkit/tests/api/test_enclosure_chassis.py, line 45 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-Ku1Ng9AvlFMx2mmGIJ0:-Ku1yaejMg6AbmBgwGX5:b-9f1ic1) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/a5b91226c5b4be2ed64f99700b2be66521d620ba/oneview_redfish_toolkit/tests/api/test_enclosure_chassis.py#L45)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

should leave Enclosure on the name, Env config may apear for another piece. Fix other place if changed here.
</blockquote></details>

Ok, changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65)*

**Comment by ffdarkpenguin** [comment]
Reviewed 4 of 14 files at r1, 8 of 10 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65)*

**Comment by ffdarkpenguin** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-:-Ku383-sQ2X8v5tHiNkB:bnfp4nl)*

**Comment by danielreed** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-:-Ku4xmsOllLOUQfpIy4d:bnfp4nl)*

**Comment by ricardoas** [comment]
:lgtm:

---

Reviewed 4 of 14 files at r1, 8 of 10 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/65#-:-Ku5RxKAOx7cQFV5CYz_:bnfp4nl)*

**Pull request merged**
