### PR TITLE
Implement ChassisCollection

### LINKED ISSUE #36: Implement ChassisCollection
As oneview-redfish-toolkit user, I access "/redfish/v1/Chassis" and receive info from all Chassis representing:
* each OneView's Server Hardware available;
* each OneView's Enclosure available;
* each OneView's Rack available.

### PR DESCRIPTION
**Pull request by llvieira**
Closes #36

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/45)

### CODE REVIEW

**Comment by ricardoas** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[oneview_redfish_toolkit/api/chassis_collection.py, line 82 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtCN_-dEoqRD3URvpO7:-KtCN_-dEoqRD3URvpO8:b-lgqe36) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/api/chassis_collection.py#L82)):*
> ```Python
> 
>         for resource in oneview_resource:
>             self.redfish["Members"].append(collections.OrderedDict())
> ```

If you swap this two lines there is no need for using index...
Create the dictionary and just append it :D

---

*[oneview_redfish_toolkit/tests/api/test_chassis_collection.py, line 69 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtCONKyPVjftlGCy4em:-KtCONKyPVjftlGCy4en:b8rjw3h) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/api/test_chassis_collection.py#L69)):*
> ```Python
>             self.chassis_collection = f.read()
> 
>     def test_class_instantiation(self):
> ```

What happens if OneView returns one of these as an empty collection? There should be a test for it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45)*

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[logging.ini, line 1 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD-SKYVFXmmrRZfn5g:-KtD-SKYVFXmmrRZfn5h:b-mg7556) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/logging.ini#L1)):*
> ```INI
> ; sections containing the entities
> ```

if ini files are going to be out of the modules makes no sense IMHO that something inside the module load those files. This is a poor design in my humble opinion.

---

*[redfish.ini, line 1 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD-vWv052NUSoH0cNd:-KtD-vWv052NUSoH0cNe:bv0a2ai) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/redfish.ini#L1)):*
> ```INI
> [redfish]
> ```

same opinion as before

---

*[oneview_redfish_toolkit/api/chassis_collection.py, line 47 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD0PevKbqIU23-F88c:-KtD0PevKbqIU23-F88d:b-u54ssx) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/api/chassis_collection.py#L47)):*
> ```Python
>         super().__init__(self.SCHEMA_NAME)
> 
>         self.server_hardware = server_hardware
> ```

in the DTMF mockup server_hardware are not listed in the chassis collection. 

---

*[oneview_redfish_toolkit/blueprints/chassis_collection.py, line 53 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD0vlzVuxyfnBq6Ac6:-KtD0vlzVuxyfnBq6Ac7:b-w35uw8) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/blueprints/chassis_collection.py#L53)):*
> ```Python
> 
>         # Gets all server hardware
>         oneview_server_hardwares = ov_client.server_hardware.get_all()
> ```

again, DMTF don't list SH in ChassisCollection

---

*[oneview_redfish_toolkit/blueprints/computer_system_collection.py, line 65 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD1yZQrZ9EWe7zvCVc:-KtD1yZQrZ9EWe7zvCVd:bkjqwp1) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/blueprints/computer_system_collection.py#L65)):*
> ```Python
>         return abort(status.HTTP_500_INTERNAL_SERVER_ERROR)
> ```

change ComputerSystemCollection while developing Chassis collection makes no sense and make everybody work much harder. IMHO we should only work on files related to a givem US in a PR. If have a fix for another job that where complete you should open a new branch.

---

*[oneview_redfish_toolkit/mockups/ChassisCollection.json, line 19 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD2jVu9NY8E9tzm5U9:-KtD2jVu9NY8E9tzm5UA:b-185oy7) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/mockups/ChassisCollection.json#L19)):*
> ```JSON
>         },
>         {
>             "@odata.id": "/redfish/v1/Chassis/30373737-3237-4D32-3230-313531354752"
> ```

should not contain server-hardware

---

*[oneview_redfish_toolkit/tests/test_util.py, line 57 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD34s7enGgY9g4TR3z:-KtD34s7enGgY9g4TR4-:b-n4ueog) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/test_util.py#L57)):*
> ```Python
>     def setUp(self):
>         self.schema_dir = './oneview_redfish_toolkit/schemas'
>         self.config_file = './redfish.ini'
> ```

already commented on this

---

*[oneview_redfish_toolkit/tests/api/test_chassis_collection.py, line 69 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtCONKyPVjftlGCy4em:-KtD3mh6zI3vtyDBnaCr:b-8ouigo) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/api/test_chassis_collection.py#L69)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

What happens if OneView returns one of these as an empty collection? There should be a test for it...
</blockquote></details>

Oneview returns are checked on blueprint tests. The API class dont know about oneview returning empty collections

---

*[oneview_redfish_toolkit/tests/api/test_computer_system_collection.py, line 39 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD3YsEcAPEu55Ehhrn:-KtD3YsEcAPEu55Ehhro:b-n4ueog) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/api/test_computer_system_collection.py#L39)):*
> ```Python
> 
>         # Loading variable in util module
>         util.load_config('redfish.ini')
> ```

already commented on this

---

*[oneview_redfish_toolkit/tests/api/test_redfish_json_validator.py, line 37 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD3a41tunxqH65nxNw:-KtD3a41tunxqH65nxNx:bjquptk) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/api/test_redfish_json_validator.py#L37)):*
> ```Python
> 
>         # Load configuration on util module
>         util.load_config('redfish.ini')
> ```

same as before

---

*[oneview_redfish_toolkit/tests/api/test_service_root.py, line 36 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD3c1jTf8dusKxge8r:-KtD3c1jTf8dusKxge8s:b-7tdrph) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/api/test_service_root.py#L36)):*
> ```Python
> 
>         # Load configuration on util module
>         util.load_config('redfish.ini')
> ```

again

---

*[oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py, line 63 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD43kMvD8tUTKH2uAG:-KtD43kMvD8tUTKH2uAH:bbn4mr2) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py#L63)):*
> ```Python
>         response = self.app.get("/redfish/v1/Chassis/")
> 
>         self.assertEqual(status.HTTP_200_OK, response.status_code)
> ```

empy stuff shoud generated an error and not a 200 page with nothing on it.

---

*[oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py, line 72 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD4M6EoEJs9F4bolrI:-KtD4M6EoEJs9F4bolrJ:bqz7x46) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py#L72)):*
> ```Python
>     def test_get_chassis_collection_fail(self, mock_get_ov_client):
>         """Tests ChassisCollection with an error"""
> ```

should test from rack error and enclosure error and generic error. this is a generic error only.

---

*[oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py, line 85 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD4JPGN2iQT3eTYXvT:-KtD4JPGN2iQT3eTYXvU:b-rl43d5) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py#L85)):*
> ```Python
>     @mock.patch.object(util, 'get_oneview_client')
>     def test_get_chassis_collection(self, mock_get_ov_client):
>         """Tests ChassisCollection with a known Server Hardware list"""
> ```

update the doc

---

*[oneview_redfish_toolkit/tests/blueprints/test_computer_system_collection.py, line 38 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD4VIKbF9W_tz1lsnG:-KtD4VIKbF9W_tz1lsnH:b-sr1ud4) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_computer_system_collection.py#L38)):*
> ```Python
> 
>         # Load config on util
>         util.load_config('redfish.ini')
> ```

same as before and you are working out of US

---

*[oneview_redfish_toolkit/tests/blueprints/test_redfish_base.py, line 17 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD4q00Z_wIbb9hYUuN:-KtD4q00Z_wIbb9hYUuO:b-nouie3) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_redfish_base.py#L17)):*
> ```Python
> # under the License.
> 
> import unittest
> ```

working out of  US 

---

*[oneview_redfish_toolkit/tests/blueprints/test_service_root.py, line 34 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD4gc4nKkejUUY2ifJ:-KtD4gc5aqKM2f6oGDFv:bht087o) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_service_root.py#L34)):*
> ```Python
> 
>         # Load config on util
>         util.load_config('redfish.ini')
> ```

same as before and again working out of your US

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45)*

**Comment by llvieira** [comment]
*[oneview_redfish_toolkit/api/chassis_collection.py, line 47 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD0PevKbqIU23-F88c:-KtD8nJmW3xT3FvNyRgb:b-ngxy4h) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/api/chassis_collection.py#L47)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

in the DTMF mockup server_hardware are not listed in the chassis collection. 
</blockquote></details>

The Oneview server_hardware in DTMF mockup is represented by blades.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45)*

**Comment by llvieira** [comment]
*[oneview_redfish_toolkit/api/chassis_collection.py, line 82 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtCN_-dEoqRD3URvpO7:-KtD94gqqx4YrhcgojxA:boiqwbo) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/api/chassis_collection.py#L82)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

If you swap this two lines there is no need for using index...
Create the dictionary and just append it :D
</blockquote></details>

Yes! thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45)*

**Comment by llvieira** [comment]
*[oneview_redfish_toolkit/blueprints/chassis_collection.py, line 53 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD0vlzVuxyfnBq6Ac6:-KtD9G2txHWTWYUpen_F:b-ngxy4h) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/blueprints/chassis_collection.py#L53)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

again, DMTF don't list SH in ChassisCollection
</blockquote></details>

The Oneview server_hardware in DTMF mockup is represented by blades.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45)*

**Comment by llvieira** [comment]
*[oneview_redfish_toolkit/mockups/ChassisCollection.json, line 19 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD2jVu9NY8E9tzm5U9:-KtD9JdHt1I1sI0q3iQZ:b-ngxy4h) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/mockups/ChassisCollection.json#L19)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

should not contain server-hardware
</blockquote></details>

The Oneview server_hardware in DTMF mockup is represented by blades.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45)*

**Comment by llvieira** [comment]
*[oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py, line 72 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD4M6EoEJs9F4bolrI:-KtDF15Z61YcIPO-A-os:bo3vl6l) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py#L72)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

should test from rack error and enclosure error and generic error. this is a generic error only.
</blockquote></details>

Thanks, done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45)*

**Comment by llvieira** [comment]
*[oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py, line 85 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD4JPGN2iQT3eTYXvT:-KtDKEkrdv5rdK87MwOW:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py#L85)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

update the doc
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45)*

**Comment by ffdarkpenguin** [comment]
:lgtm:

---

Review status: 16 of 20 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-:-KtGmb80m9dNo4K-v2om:bnfp4nl)*

**Comment by ricardoas** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[logging.ini, line 1 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD-SKYVFXmmrRZfn5g:-KtIcOCmUJLr8WMojTqN:b-am6x0g) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/logging.ini#L1)):*
> opinion
It seems more adequate to me to leave configuration files out of code folder. "*.conf" files are frequently inside /etc/ folder in linux for example, while code is generally in /var/lib or /usr/lib

---

*[oneview_redfish_toolkit/tests/test_util.py, line 57 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD34s7enGgY9g4TR3z:-KtIdHLuPO0bw03zJyZb:bqmof50) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/test_util.py#L57)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

already commented on this
</blockquote></details>

same opinion here... and would go even further on never depending on external configuration on tests. Mocks are a dev's best friend!

---

*[oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py, line 63 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD43kMvD8tUTKH2uAG:-KtDUvBmxKJpesC4RTlG:b-lr4f76) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py#L63)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

empy stuff shoud generated an error and not a 200 page with nothing on it.
</blockquote></details>

does oneview gives an exception when asking for a list of resources that can be empty? in fact this will be empty only if the admin physically removes all server hardware from the enclosure... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-:-KtIdzvp3li4dr58KYEu:bnfp4nl)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py, line 63 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-KtD43kMvD8tUTKH2uAG:-KtIfwn-7aUqHpqLc1et:b-7m99co) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/688aad82975e5ae74f66ef833c888fdb9102106b/oneview_redfish_toolkit/tests/blueprints/test_chassis_collection.py#L63)):*
> does oneview gives an exception when asking for a list of resources that can be empty?
When a list of resources is empty, the oneview return a empty list, not an exception. But I treated this to return 404 status code...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45)*

**Comment by danielreed** [comment]
:lgtm:

---

Reviewed 17 of 22 files at r1, 2 of 4 files at r2, 4 of 4 files at r3.
Review status: 17 of 23 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-:-KtTD1MojGUOhdlh0dVC:bnfp4nl)*

**Comment by ricardoas** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r4.
Review status: 19 of 23 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/45#-:-Ktlb4BSahsNxNR33A1e:bnfp4nl)*

**Pull request merged**
