### PR TITLE
Blade manager firmware version

### PR DESCRIPTION
**Pull request by bsoutham**
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/92)

### CODE REVIEW

**Comment by ffdarkpenguin** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/92)*

**Comment by ffdarkpenguin** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/92#-:-Kv95Q5P8kaOnOfTSSuV:bnfp4nl)*

**Comment by llvieira** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/92#-:-Kv97S4pJrdoop_kjPcO:bnfp4nl)*

**Comment by danielreed** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/92#-:-Kv9BI9KWMbT2xNmDxYq:bnfp4nl)*

**Pull request merged**
