### PR TITLE
Implement ManagerCollection

### LINKED ISSUE #55: Implement ManagerCollection
As oneview-redfish-toolkit user, I access "/redfish/v1/Managers" and receive info from all Managers corresponding to:

each OneView's Server Hardware available;
each OneView's Enclosure available.

### PR DESCRIPTION
**Pull request by llvieira**
Closes #55.
Created class and blueprint of ManagerCollection and its tests. 

---
[Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/71)

### CODE REVIEW

**Comment by ffdarkpenguin** [comment]
Review status: 0 of 6 files reviewed at latest revision, 10 unresolved discussions.

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 55 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTCq9volI5gM1VmlHj:-KuTCq9wy1BgzVzRl5Jb:b-iadk87) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/api/manager_collection.py#L55)):*
> ```Python
>         self.redfish["Members"] = list()
>         self._set_redfish_members()
>         self.redfish["@odata.id"] = "/redfish/v1/Managers"
> ```

missing @odata.context

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 66 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTDwS0Mog8XBj8RU-1:-KuTDwS0Mog8XBj8RU-2:bjsajdx) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/api/manager_collection.py#L66)):*
> ```Python
>         """
> 
>         self._set_resource_links(self.enclosures)
> ```

I really don't like this kind of function. It makes the code harder to understand as: 
1. you see _set_redfish_menbers at __init__ so I have to stop undertanding init to see what it does.
2. then you only call this function once, at init
3. the you wrote 12 lines of code to avoid putting 2 lines in the init
   2 lines to set self.enclosure and self.server_hardware
   9 lines of the function including docs and comments
   1 line to call the function
Can you please draw what the gain here because I really can't see.
And finally this function only calls another function.
If this is a design patter it the worse ever, please tell me the name because I have to read it, and criticize if to see if it improves.
To function are useful if:
1. you gonna do that think at LEAST more than once (don't repeat yourself principle)
2. the things you gonna put in a function is very complex and its better a function with a meaningful name that hard to get code.

To me the code in the _set_resource_links itself should be in the init. The are very simple code with no need to have this 2 extra functions
Finally this is just my opinion. What looks ugly to me in a code. Im already setting this debate as solved. If you change it or not makes no difference

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 75 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTGienX9gqhS2ncBXK:-KuTGieocRC9gZT6MwbQ:b-di3rx3) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/api/manager_collection.py#L75)):*
> ```Python
>             link_dict = collections.OrderedDict()
>             link_dict["@odata.id"] = \
>                 "/redfish/v1/Chassis/" + resource["uuid"]
> ```

This link is wrong, should be manager

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 81 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTGodxr-CUxB58y_AS:-KuTGodxr-CUxB58y_AT:b-sdo458) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/api/manager_collection.py#L81)):*
> ```Python
>         """Gets the length of redfish members"""
> 
>         return len(self.server_hardware) + len(self.enclosures)
> ```

This also is so unnecessary IMHO.
In the math point of view: 4 lines to write the function, 1 line to call it, to replace 1 line of code.

---

*[oneview_redfish_toolkit/blueprints/manager_collection.py, line 95 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTJeMddEBBQmy4F2WQ:-KuTJeMeJ5ZWV2tZKXkR:b-um48b5) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/blueprints/manager_collection.py#L95)):*
> ```Python
>     """Check if some oneview resource is empty and raise an exception"""
> 
>     if not server_hardwares:
> ```

same as the situation on the API. creating a function to be called only one time.
He goes all arguments I used before PLUS:
if you tested each result after calling OV client if enclosure is empty you didn't need to call the function to get the server_hadware and didn't have to call this function and could have aborted earlier and improve the performance of your system.

---

*[oneview_redfish_toolkit/mockups/ManagerCollection.json, line 88 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTHR-uLnyXlCxZsGG6:-KuTHR-uLnyXlCxZsGG7:b-iadk87) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/mockups/ManagerCollection.json#L88)):*
> ```JSON
>         }
>     ],
>     "@odata.id": "/redfish/v1/Managers"
> ```

missing @odata.context

---

*[oneview_redfish_toolkit/tests/api/manager_collection.py, line 86 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTHj2MwSJhF9-iHBD6:-KuTHj2MwSJhF9-iHBD7:b-v0tst0) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/api/manager_collection.py#L86)):*
> ```Python
>             self.fail("Failed to serialize. Error: ".format(e))
> 
>         self.assertEqual(json_str, self.manager_collection)
> ```

You are not testing for server_hardware and enclosures not found and some other exception. You questioned Daniel about it on thermal patch

---

*[oneview_redfish_toolkit/tests/blueprints/manager_collection.py, line 80 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTILEVOwzzad5HqyOc:-KuTILEVOwzzad5HqyOd:b8b3wr5) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/blueprints/manager_collection.py#L80)):*
> ```Python
>     @mock.patch.object(util, 'get_oneview_client')
>     def test_get_server_hardwares_empty(self, mock_get_ov_client):
>         """Tests ManagerCollection with an empty list"""
> ```

an empty ???? list
which list?

---

*[oneview_redfish_toolkit/tests/blueprints/manager_collection.py, line 96 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTIQTrC7yWAuaAwhLN:-KuTIQTsjO8CYyPw5yrg:bnj7hl0) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/blueprints/manager_collection.py#L96)):*
> ```Python
>     @mock.patch.object(util, 'get_oneview_client')
>     def test_get_enclosures_empty(self, mock_get_ov_client):
>         """Tests ManagerCollection with an empty list"""
> ```

same as above

---

*[oneview_redfish_toolkit/tests/blueprints/manager_collection.py, line 99 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTJ6bnmehR4347_e-Q:-KuTJ6boiIbuKBcp_FoX:b-70jhq0) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/blueprints/manager_collection.py#L99)):*
> ```Python
> 
>         client = mock_get_ov_client()
>         client.enclosures.get_all.return_value = []
> ```

its not working as expected. you are not returning a valid value to server_hardware_get_all. You dont know what being returned and as your test tests for server_hardware before testing for enclosure your could is retuning a 404 but not where you expect(it 's from if not server_hardware). When we add correct messages to 404 you will see this error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by ricardoas** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 66 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTDwS0Mog8XBj8RU-1:-KuUiDA9Bq_1b2vpsVjx:bpbre2g) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/api/manager_collection.py#L66)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

I really don't like this kind of function. It makes the code harder to understand as: 
1. you see _set_redfish_menbers at __init__ so I have to stop undertanding init to see what it does.
2. then you only call this function once, at init
3. the you wrote 12 lines of code to avoid putting 2 lines in the init
   2 lines to set self.enclosure and self.server_hardware
   9 lines of the function including docs and comments
   1 line to call the function
Can you please draw what the gain here because I really can't see.
And finally this function only calls another function.
If this is a design patter it the worse ever, please tell me the name because I have to read it, and criticize if to see if it improves.
To function are useful if:
1. you gonna do that think at LEAST more than once (don't repeat yourself principle)
2. the things you gonna put in a function is very complex and its better a function with a meaningful name that hard to get code.

To me the code in the _set_resource_links itself should be in the init. The are very simple code with no need to have this 2 extra functions
Finally this is just my opinion. What looks ugly to me in a code. Im already setting this debate as solved. If you change it or not makes no difference
</blockquote></details>

Lucas, I'd advise you to aim for "keep it simple" and extract a method only for reusing purposes... is this being reused somewhere else?

---

*[oneview_redfish_toolkit/tests/api/manager_collection.py, line 86 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTHj2MwSJhF9-iHBD6:-KuUitwPAwbhVY6aQknB:b32v57) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/api/manager_collection.py#L86)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

You are not testing for server_hardware and enclosures not found and some other exception. You questioned Daniel about it on thermal patch
</blockquote></details>

+1

---

*[oneview_redfish_toolkit/tests/blueprints/manager_collection.py, line 99 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTJ6bnmehR4347_e-Q:-KuUjA7TskAXSp2vai8Z:bvmcz40) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/blueprints/manager_collection.py#L99)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

its not working as expected. you are not returning a valid value to server_hardware_get_all. You dont know what being returned and as your test tests for server_hardware before testing for enclosure your could is retuning a 404 but not where you expect(it 's from if not server_hardware). When we add correct messages to 404 you will see this error.
</blockquote></details>

If you import an empty enclosure to OneView it should return an empty server hardware list, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 55 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTCq9volI5gM1VmlHj:-KuUkM-_X4TXrIh_fG5W:b-896fja) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/api/manager_collection.py#L55)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

missing @odata.context
</blockquote></details>

Done!

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 75 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTGienX9gqhS2ncBXK:-KuUk9e4e8EQYdsdPppr:bkkvffe) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/api/manager_collection.py#L75)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

This link is wrong, should be manager
</blockquote></details>

Okay, changed!

---

*[oneview_redfish_toolkit/mockups/ManagerCollection.json, line 88 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTHR-uLnyXlCxZsGG6:-KuUkIGm8lKkmgx-92Zw:b-896fja) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/mockups/ManagerCollection.json#L88)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

missing @odata.context
</blockquote></details>

Done!

---

*[oneview_redfish_toolkit/tests/api/manager_collection.py, line 86 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTHj2MwSJhF9-iHBD6:-KuUi3OA6PHy4MbBrbk-:b-d0ojrn) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/api/manager_collection.py#L86)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

+1
</blockquote></details>

But the way in that the Thermal class is instantiated is very different of the way that ManagerCollection is instantiated, so in Thermal it's needed to test more things. I didn't understand you very well, since this is the way that we are testing the classes from the beginning...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[oneview_redfish_toolkit/tests/blueprints/manager_collection.py, line 80 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTILEVOwzzad5HqyOc:-KuV2CQPsYGLRhajsdhF:bny7ovh) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/blueprints/manager_collection.py#L80)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

an empty ???? list
which list?
</blockquote></details>

okay, now I have specified what is the list.

---

*[oneview_redfish_toolkit/tests/blueprints/manager_collection.py, line 96 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTIQTrC7yWAuaAwhLN:-KuV2EKWNdmYWb1HmXtB:b-t0ivdr) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/blueprints/manager_collection.py#L96)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

same as above
</blockquote></details>

okay, now I have specified what is the list

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 66 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTDwS0Mog8XBj8RU-1:-KuV3NOBL7GJHBK5sUhg:b-t2oqze) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/api/manager_collection.py#L66)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

Lucas, I'd advise you to aim for "keep it simple" and extract a method only for reusing purposes... is this being reused somewhere else?
</blockquote></details>

The method _set_resource_links is good because the same 'for loop' is used as for enclosure as for server hardware, it is a method to reuse of code.

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 81 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTGodxr-CUxB58y_AS:-KuV2d0FBCG-vy3sNGKX:boojokg) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/api/manager_collection.py#L81)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

This also is so unnecessary IMHO.
In the math point of view: 4 lines to write the function, 1 line to call it, to replace 1 line of code.
</blockquote></details>

Okay, removed method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[oneview_redfish_toolkit/blueprints/manager_collection.py, line 95 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTJeMddEBBQmy4F2WQ:-KuV5YdTKozQ2euPdc4n:b-k1hgq2) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/blueprints/manager_collection.py#L95)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

same as the situation on the API. creating a function to be called only one time.
He goes all arguments I used before PLUS:
if you tested each result after calling OV client if enclosure is empty you didn't need to call the function to get the server_hadware and didn't have to call this function and could have aborted earlier and improve the performance of your system.
</blockquote></details>

Great! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by llvieira** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[oneview_redfish_toolkit/tests/blueprints/manager_collection.py, line 99 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTJ6bnmehR4347_e-Q:-KuVAQNbO9zKsT5PIyKd:buwic33) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/blueprints/manager_collection.py#L99)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

If you import an empty enclosure to OneView it should return an empty server hardware list, right?
</blockquote></details>

Yeah... adapted! thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by ffdarkpenguin** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[oneview_redfish_toolkit/tests/api/manager_collection.py, line 86 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuTHj2MwSJhF9-iHBD6:-KuVGRLb_DUoQ_Qg3hNm:b-xce9p5) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/c316b35e2b81c489419d38f60e0783494788f8cc/oneview_redfish_toolkit/tests/api/manager_collection.py#L86)):*
<details><summary><i>Previously, llvieira (Lucas Lima Vieira) wrote…</i></summary><blockquote>

But the way in that the Thermal class is instantiated is very different of the way that ManagerCollection is instantiated, so in Thermal it's needed to test more things. I didn't understand you very well, since this is the way that we are testing the classes from the beginning...
</blockquote></details>

agree, this kind of test should be done on the blueprint

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by ffdarkpenguin** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by ffdarkpenguin** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-:-KuVHVE1ruMd_g1TmPIX:bnfp4nl)*

**Comment by danielreed** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 33 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuVg_SH-Hp-XVvtJtbJ:-KuVg_SH-Hp-XVvtJtbK:b7ypapa) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/0e926d73e4aa34d94ee1853d90cf48f6d3873256/oneview_redfish_toolkit/api/manager_collection.py#L33)):*
> ```Python
> 
>     def __init__(self, server_hardware, enclosures):
>         """ChassisCollection constructor
> ```

Should be ManagerCollection constructor, looks like these comments need to be updated to not reference ChassisCollection

---

*[oneview_redfish_toolkit/blueprints/manager_collection.py, line 74 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuVhd1j7aHnvUMRNa1O:-KuVhd1j7aHnvUMRNa1P:b-nhshr4) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/0e926d73e4aa34d94ee1853d90cf48f6d3873256/oneview_redfish_toolkit/blueprints/manager_collection.py#L74)):*
> ```Python
>                 "server-hardwares", "oneview-result")
> 
>         # Build Chassis Collection object and validates it
> ```

Build the Manager Collection, change cc to mc

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by llvieira** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[oneview_redfish_toolkit/api/manager_collection.py, line 33 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuVg_SH-Hp-XVvtJtbJ:-KuZZy_YwV5gWUsZwQIE:b-bw8e1h) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/0e926d73e4aa34d94ee1853d90cf48f6d3873256/oneview_redfish_toolkit/api/manager_collection.py#L33)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

Should be ManagerCollection constructor, looks like these comments need to be updated to not reference ChassisCollection
</blockquote></details>

Updated!

---

*[oneview_redfish_toolkit/blueprints/manager_collection.py, line 74 at r2](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-KuVhd1j7aHnvUMRNa1O:-KuZ_1uxdnP0kiExcDKT:b-bw8e1h) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/0e926d73e4aa34d94ee1853d90cf48f6d3873256/oneview_redfish_toolkit/blueprints/manager_collection.py#L74)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

Build the Manager Collection, change cc to mc
</blockquote></details>

Updated!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by ffdarkpenguin** [comment]
Reviewed 2 of 6 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by danielreed** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-:-KuZnxfXlAbcdZzoB4bJ:bnfp4nl)*

**Comment by ffdarkpenguin** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71)*

**Comment by ricardoas** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/71#-:-KuuRdH6os8pnrpLJpTD:bnfp4nl)*

**Pull request merged**
