### PR TITLE
report BMC firmware in blade_manager

### PR DESCRIPTION
**Pull request by bsoutham**
change blade_manager to report the ilo firmware version instead of the OV firmware version

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/89)

### CODE REVIEW

**Comment by llvieira** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/89)*

**Comment by ffdarkpenguin** [comment]
from slack @general channel:
@blaine.southam your change failed because you changed a class and didn't change the respective test. Lookup for the correct mockup in the mockup_redfish dir and update the json files with the new names. Also recommend you to run a tox locally to test the changes before submitting so it not fails on the CI.

The version where hardcoded to OV version based on @danielreed info. If you think it´s better to use the one you set there's no need for the variable ov_version. Remove this variable will force you to correct the blueprint and all tests related that use this variable.

If you have any question let me know, I´ve implemented these and can answer anything you need and help you if you like

**Comment by ffdarkpenguin** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[oneview_redfish_toolkit/api/blade_manager.py, line 42 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/89#-Kv42tdCfOH1LqC6e3CP:-Kv42tdCfOH1LqC6e3CQ:b-c9l8my) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/9c7c8d897896d607bd6a68b4353f51a54db59190/oneview_redfish_toolkit/api/blade_manager.py#L42)):*
> ```Python
>         super().__init__(server_hardware, ov_version)
> 
>         self.redfish["FirmwareVersion"] = server_hardware['mpFirmwareVersion']
> ```

needs to fix the tests. Also would be nice clean the code: remove ov_version from init definition e fix where error are going to pop up. Also you can pass server_hardware['mpFirmwareVersion'] to super().init to set it super class.  If this should be done to enclosure as well, consider removing ov_version from all objects and set FirmwareVersion as you did on enclosure_manager.py

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/89)*

**Comment by bsoutham** [comment]
fixed test cases. 

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[oneview_redfish_toolkit/api/blade_manager.py, line 42 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/89#-Kv42tdCfOH1LqC6e3CP:-Kv8cLrX8uI5g85Sf1xU:b4tipjs) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/9c7c8d897896d607bd6a68b4353f51a54db59190/oneview_redfish_toolkit/api/blade_manager.py#L42)):*
<details><summary><i>Previously, ffdarkpenguin wrote…</i></summary><blockquote>

needs to fix the tests. Also would be nice clean the code: remove ov_version from init definition e fix where error are going to pop up. Also you can pass server_hardware['mpFirmwareVersion'] to super().init to set it super class.  If this should be done to enclosure as well, consider removing ov_version from all objects and set FirmwareVersion as you did on enclosure_manager.py
</blockquote></details>

fixed test cases.  will clean up code in a different PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/89#-:-Kv8c6WK9RnoSDCfuJQk:b-7h8jmw)*

**Comment by ffdarkpenguin** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/89#-:-Kv8cmTCTytSk9ZoByNn:bnfp4nl)*

**Pull request merged**
