### PR TITLE
Add RackChassis

### LINKED ISSUE #39: Implement Rack Chassis
As oneview-redfish-toolkit, I access "/redfish/v1/Chassis/<rack_uuid>" and receive basic information of the OneView's Rack equivalent Chassis and a link back to all Enclosures Chassis is contains.

### PR DESCRIPTION
**Pull request by ffdarkpenguin**
closes #39

---
This change is [Reviewable](https://reviewable.io/reviews/hewlettpackard/oneview-redfish-toolkit/66)

### CODE REVIEW

**Comment by llvieira** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/66#-:-Ku4j8GlJO1GslaEZpvK:bnfp4nl)*

**Comment by danielreed** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[oneview_redfish_toolkit/mockups/RedfishRack.json, line 1 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/66#-Ku4yX0hJcX0arlqQrSO:-Ku4yX0hJcX0arlqQrSP:b-izbwjr) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/eeba7ec50853ab0c13ed8168849a31ae15fae820/oneview_redfish_toolkit/mockups/RedfishRack.json#L1)):*
> ```JSON
> {
> ```

I think this should be named RackChassis.  I thought we were trying to avoid putting Redfish or OneView into the names of the mockups.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/66)*

**Comment by ricardoas** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[oneview_redfish_toolkit/mockups/RedfishRack.json, line 1 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/66#-Ku4yX0hJcX0arlqQrSO:-Ku5WTv4I-sDfXI-V-s-:b-pbdqzg) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/eeba7ec50853ab0c13ed8168849a31ae15fae820/oneview_redfish_toolkit/mockups/RedfishRack.json#L1)):*
<details><summary><i>Previously, danielreed (Daniel Reed) wrote…</i></summary><blockquote>

I think this should be named RackChassis.  I thought we were trying to avoid putting Redfish or OneView into the names of the mockups.
</blockquote></details>

Agreed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/66)*

**Comment by ffdarkpenguin** [comment]
Review status: 0 of 31 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[oneview_redfish_toolkit/mockups/RackChassis.json, line 1 at r1](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/66#-Ku4yX0hJcX0arlqQrSO:-KuSs4Hy3Mgb6BemUGWG:b-896fix) ([raw file](https://github.com/hewlettpackard/oneview-redfish-toolkit/blob/eeba7ec50853ab0c13ed8168849a31ae15fae820/oneview_redfish_toolkit/mockups/RackChassis.json#L1)):*
<details><summary><i>Previously, ricardoas (Ricardo Araújo) wrote…</i></summary><blockquote>

Agreed!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/66)*

**Comment by ricardoas** [comment]
:lgtm:

---

Reviewed 4 of 17 files at r2, 19 of 20 files at r3, 1 of 3 files at r4, 1 of 2 files at r5, 2 of 7 files at r6, 7 of 8 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/66#-:-KuUbOzcIjAsH_YCpbWS:bnfp4nl)*

**Comment by danielreed** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/hewlettpackard/oneview-redfish-toolkit/66#-:-KuUgwJwVxOked-__PGt:bnfp4nl)*

**Pull request merged**
